const char* root_ca = 
"-----BEGIN CERTIFICATE-----\n" \
"MIIDCTCCAfGgAwIBAgIUPhagksAwvmhshBPd7FfBh0kG0iAwDQYJKoZIhvcNAQEL\n" \
"BQAwFDESMBAGA1UEAwwJMTAuNDIuMC4xMB4XDTI2MDMzMDE0MjEwN1oXDTI3MDMz\n" \
"MDE0MjEwN1owFDESMBAGA1UEAwwJMTAuNDIuMC4xMIIBIjANBgkqhkiG9w0BAQEF\n" \
"AAOCAQ8AMIIBCgKCAQEA10u5IObT/2Vvg4D5MhTKlKcSiu9WSk9WHt1herxs+aWD\n" \
"tEi3I/lW4pT8D7X7LrxBsS9aOnIMwdtWPLQFdtOWeTTGk7wpAD7gfiAIt70rxO5j\n" \
"sOwIgfe0WWsk4GUe+S+ygtCEGTsmj3JKZhLagaLzXdHfk66SoXr+guHKlhWYRZX/\n" \
"ESlPhzeBHz0QUBne8XULTY/bgDOT3DDpKpeK4fM4lMpAH72oYomwuvDRVxw9hkeJ\n" \
"RrHFVwKLbGpjmnnK/n9VM9ToL17elNLWqrgTMEhYEXDaOGZYhVSBPl1ScUZkSLIU\n" \
"rgEb2F5T6wlZGAII4jrZr6nrczV5+AXmKOVBZc2iJwIDAQABo1MwUTAdBgNVHQ4E\n" \
"FgQULR2TqpB0lypElAUWF/NsaaeA6ZYwHwYDVR0jBBgwFoAULR2TqpB0lypElAUW\n" \
"F/NsaaeA6ZYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOCAQEAe+Cx\n" \
"MNuM7e9xrQ9jje9ZsgspXks4BjiT4yHoLMwnQr7rN6er1uRf2HD2B+bAkJJ71S4o\n" \
"TLk0EKQXTwvDBsqeO7uxn/IUgE3KmgVbMbUakdF4au0jtXe/RVg+by+AyukXmHyU\n" \
"DdbElCSzYfsZQtkLpjctxtD2Fek1jqeYAMTOdEMYdcGkhbS6R3KEo4yKSRwvukoA\n" \
"zPyYSDv+mJEu/gBA4QwtP+5/7FxjbDnBmeDSdAkp7jy8Fp6xlbTs27n2rpjh6S5o\n" \
"bFGGmc9+A2vE4LKCVg3gOZQb91aVTpdxmos5a2KdjGihsgpduSIj24vuYA5Hx41d\n" \
"PW3My4cXLSQNiG7wEw==\n" \
"-----END CERTIFICATE-----\n";